name: wings
version: '${version}'
main: com.tristansmp.wings.Wings
api-version: 1.19

commands:
  link:
    description: TSMP link command
    usage: /link <code>
    permission: wings.link
  deposit:
    description: Deposit diamonds to the TSMP market
    usage: /deposit <amount>
    permission: wings.deposit
  delivery:
    description: Get items delivered to you from the TSMP market
    usage: /deliver
    permission: wings.deliver