name: wings
version: '${version}'
main: com.tristansmp.wings.Wings
api-version: 1.19

commands:
  link:
    description: TSMP link command
    usage: /link <code>
    permission: wings.link
  deposit:
    description: Deposit diamonds to the TSMP market
    usage: /deposit <amount>
    permission: wings.deposit
  deliver:
    description: Get items delivered to you from the TSMP market
    usage: /deliver
    permission: wings.deliver
  package:
    description: Package an item to sell on the TSMP market
    usage: /package <price>
    permission: wings.package
  create-sign-shop:
    description: Create a sign shop
    usage: /create-sign-shop <b64key>
    permission: wings.create-sign-shop
  ott:
    description: Get an OTT
    usage: /ott
    permission: wings.ott
  wi:
    description: Get a Wings Item
    usage: /wi <item>
    permission: wings.wi
  spawn:
    description: Go to TSMP's current spawn, or previous spawns.
    usuage: /spawn
    permission: wings.spawn